### ISSUE TITLE
Intro screen has some bugs

### ISSUE THREAD

**Issue by Gregorie** [Bennik2000/DHBWStudentInformationApp#59] opened 2020-10-06 21:29 UTC
## Expected Behavior
Content should be visibile.

## Current Behavior
In landscape orientation some content is concealed or is not on the screen.

## Steps to Reproduce
1. Open app for the first time
2. Turn screen to landscape orientation

![Screenshot_20201006-230545](https://user-images.githubusercontent.com/5672294/95261554-e47d5600-082a-11eb-8503-4667a07371bf.jpg)
Text is concealed :arrow_up:

"Next" button and page indicator are missing ⬇️  

![Screenshot_20201006-231923](https://user-images.githubusercontent.com/5672294/95261561-e6dfb000-082a-11eb-927b-44377a15dd39.jpg)

## Context (Environment)
-  Version 1.0.14
- Android 8 & 9

**Comment by Bennik2000** [comment] 2020-10-06 22:06
Well, those are some serious UI bugs which could prevent users from using this app. They install it, see that it is broken and uninstall it immediately.

Possible fix for phones:
- only allow portrait mode

Possible fixes for tablets:
- only allow portrait mode in the onboarding page
- fix the misplaced UI elements

**Comment by Bennik2000** [comment] 2020-10-06 23:02
For phones the issue is fixed by only allowing portrait mode while onboarding.

For tablets the issue is fixed by adjusting the placement of the UI elements. The screenshot shows the correct placed elements:


![Screenshot_1602024024](https://user-images.githubusercontent.com/8039939/95267507-b3eee980-0835-11eb-8642-b5609ba338c2.png)

**Closed by Bennik2000** 2020-10-06 23:02 UTC
